# Generated by Django 5.2.6 on 2025-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('detected_label', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
